#include <gtest/gtest.h>
#include "cli/ReplClient.h"
#include "workspace/WorkspaceManager.h"
#include "testing/TestGenerator.h"
#include <filesystem>
#include <fstream>

using namespace aios;

// ─────────────────────────────────────────────────────────────
// 1. ReplClient Unit Tests
// ─────────────────────────────────────────────────────────────

TEST(ReplClientTest, ColorizeProducesAnsiCodes) {
    std::string colored = ReplClient::colorize("hello", 31);
    // ANSI escape start must be present in a TTY context
    // Without TTY detection (CI), just verify output is non-empty
    EXPECT_FALSE(colored.empty());
    EXPECT_NE(colored.find("hello"), std::string::npos);
}

TEST(ReplClientTest, AgentTagContainsRole) {
    std::string tag = ReplClient::agentTag("Planner");
    EXPECT_NE(tag.find("Planner"), std::string::npos);
}

TEST(ReplClientTest, DimTextContainsContent) {
    std::string dim = ReplClient::dimText("some context");
    EXPECT_NE(dim.find("some context"), std::string::npos);
}

// ─────────────────────────────────────────────────────────────
// 2. WorkspaceManager Unit Tests
// ─────────────────────────────────────────────────────────────

TEST(WorkspaceManagerTest, InitializeFailsForNonRepo) {
    WorkspaceConfig cfg;
    cfg.repo_path = std::filesystem::temp_directory_path().string() + "/not_a_repo";
    WorkspaceManager mgr(cfg);
    // Should return false since temp dir is not a git repo
    bool ok = mgr.initialize();
    EXPECT_FALSE(ok);
}

TEST(WorkspaceManagerTest, InitializeSucceedsForValidRepo) {
    // Use the project's own repo if available
    WorkspaceConfig cfg;
    cfg.repo_path = "c:\\Users\\kaush\\Downloads\\MINIcodingAgent";
    cfg.auto_cleanup = false;
    WorkspaceManager mgr(cfg);
    bool ok = mgr.initialize();
    // Either the path is a git repo (success) or not in CI — just verify no crash
    EXPECT_TRUE(ok || !ok);
}

TEST(WorkspaceManagerTest, ListSandboxesEmptyInitially) {
    WorkspaceConfig cfg;
    cfg.repo_path = "c:\\Users\\kaush\\Downloads\\MINIcodingAgent";
    WorkspaceManager mgr(cfg);
    EXPECT_TRUE(mgr.listSandboxes().empty());
}

// ─────────────────────────────────────────────────────────────
// 3. TestGenerator Unit Tests
// ─────────────────────────────────────────────────────────────

TEST(TestGeneratorTest, GenerateTestCaseForMethod) {
    TestGenerator gen;
    ParsedSymbol sym;
    sym.qualified_name = "aios::VectorStore::search";
    sym.return_type    = "std::vector<VectorSearchResult>";
    sym.param_types    = {"std::string_view", "size_t"};
    sym.is_method      = true;
    sym.class_name     = "VectorStore";
    sym.file_path      = "vector/VectorStore.h";

    auto tc = gen.generateTestCase(sym, "AutoGenerated");

    EXPECT_EQ(tc.test_suite_name, "AutoGenerated");
    EXPECT_FALSE(tc.test_name.empty());
    EXPECT_NE(tc.test_body.find("VectorStore"), std::string::npos);
    EXPECT_FALSE(tc.include_headers.empty());
}

TEST(TestGeneratorTest, GenerateTestCaseForFreeFunction) {
    TestGenerator gen;
    ParsedSymbol sym;
    sym.qualified_name = "aios::VectorStore::cosineSimilarity";
    sym.return_type    = "float";
    sym.param_types    = {"const float*", "const float*", "size_t"};
    sym.is_method      = false;

    auto tc = gen.generateTestCase(sym, "VectorSuite");

    EXPECT_EQ(tc.test_suite_name, "VectorSuite");
    EXPECT_NE(tc.test_body.find("result"), std::string::npos);
}

TEST(TestGeneratorTest, WriteTestFileCreatesFile) {
    TestGenerator gen;
    ParsedSymbol sym;
    sym.qualified_name = "aios::TestFunc";
    sym.return_type    = "bool";
    sym.param_types    = {"int"};
    sym.is_method      = false;

    std::string output_dir = std::filesystem::temp_directory_path().string();
    auto result = gen.generateTests({sym}, output_dir, "WriteTest");

    EXPECT_TRUE(result.success);
    EXPECT_TRUE(std::filesystem::exists(result.output_file_path));
    // Cleanup
    std::filesystem::remove(result.output_file_path);
}

TEST(TestGeneratorTest, ParseGccDiagnosticErrors) {
    TestGenerator gen;
    std::string output =
        "/home/user/project/src/foo.cpp:42:10: error: 'bar' was not declared in this scope\n"
        "/home/user/project/src/foo.cpp:55:5: warning: unused variable 'x' [-Wunused-variable]\n";

    auto report = gen.parseDiagnostics(output, "gcc");

    EXPECT_TRUE(report.has_errors);
    EXPECT_EQ(report.error_count, 1);
    EXPECT_EQ(report.warning_count, 1);
    ASSERT_FALSE(report.diagnostics.empty());

    const auto& d = report.diagnostics[0];
    EXPECT_EQ(d.line, 42);
    EXPECT_EQ(d.column, 10);
    EXPECT_EQ(d.severity, DiagnosticSeverity::Error);
    EXPECT_NE(d.message.find("bar"), std::string::npos);
    EXPECT_FALSE(d.suggested_fix.empty());
}

TEST(TestGeneratorTest, ParseMsvcDiagnosticErrors) {
    TestGenerator gen;
    std::string output =
        "C:\\project\\src\\bar.cpp(17): error C2065: 'foo': undeclared identifier\n"
        "C:\\project\\src\\bar.cpp(30): warning C4101: 'x': unreferenced local variable\n";

    auto report = gen.parseDiagnostics(output, "msvc");

    EXPECT_TRUE(report.has_errors);
    EXPECT_EQ(report.error_count, 1);
    EXPECT_EQ(report.warning_count, 1);
    EXPECT_EQ(report.diagnostics[0].error_code, "C2065");
    EXPECT_EQ(report.diagnostics[0].line, 17);
}

TEST(TestGeneratorTest, RemediationActionsIsValidJson) {
    TestGenerator gen;
    DiagnosticsReport report;
    CompilerDiagnostic d;
    d.severity = DiagnosticSeverity::Error;
    d.file_path = "src/foo.cpp";
    d.line = 10;
    d.message = "undefined reference to 'bar'";
    d.suggested_fix = "Add missing implementation or link library.";
    report.diagnostics.push_back(d);
    report.has_errors = true;
    report.error_count = 1;

    std::string json_out = gen.toRemediationActions(report);
    EXPECT_FALSE(json_out.empty());
    EXPECT_NE(json_out.find("fix_compiler_error"), std::string::npos);
    EXPECT_NE(json_out.find("undefined reference"), std::string::npos);
}

TEST(TestGeneratorTest, EmptyDiagnosticsNoErrors) {
    TestGenerator gen;
    auto report = gen.parseDiagnostics("Build succeeded.\n[ 100%] Linking\n", "gcc");
    EXPECT_FALSE(report.has_errors);
    EXPECT_EQ(report.error_count, 0);
}
