#pragma once

#include <string>
#include <string_view>
#include <vector>
#include <unordered_map>
#include <optional>

namespace aios {

// ─────────────────────────────────────────────────────────────
// Compiler Diagnostic Structures
// ─────────────────────────────────────────────────────────────

enum class DiagnosticSeverity {
    Note,
    Warning,
    Error,
    Fatal
};

struct CompilerDiagnostic {
    std::string file_path;
    int line = 0;
    int column = 0;
    DiagnosticSeverity severity = DiagnosticSeverity::Error;
    std::string error_code;       // e.g. "E0349", "W4", "clang-diagnostic-unused"
    std::string message;
    std::string source_context;   // surrounding source line
    std::string suggested_fix;    // parsed from diagnostic notes
};

struct DiagnosticsReport {
    bool has_errors = false;
    int error_count = 0;
    int warning_count = 0;
    std::vector<CompilerDiagnostic> diagnostics;
    std::string raw_output;

    std::vector<CompilerDiagnostic> errors() const;
    std::vector<CompilerDiagnostic> warnings() const;
    std::string toSummaryString() const;
};

// ─────────────────────────────────────────────────────────────
// Test Case Scaffolds
// ─────────────────────────────────────────────────────────────

struct ParsedSymbol {
    std::string qualified_name;    // e.g. "aios::VectorStore::search"
    std::string return_type;
    std::vector<std::string> param_types;
    std::string file_path;
    int line = 0;
    bool is_method = false;
    std::string class_name;
};

struct GeneratedTestCase {
    std::string test_suite_name;
    std::string test_name;
    std::string test_body;
    std::vector<std::string> include_headers;
    std::string namespace_str;
};

struct TestGenerationResult {
    bool success = false;
    std::string output_file_path;
    std::vector<GeneratedTestCase> test_cases;
    std::string error_message;
};

// ─────────────────────────────────────────────────────────────
// Test Generator & Diagnostics Engine
// ─────────────────────────────────────────────────────────────

/**
 * @brief Automated Test Case Generator and Semantic Diagnostics Engine
 *
 * Provides:
 * - GoogleTest C++ test scaffold generation from parsed AST symbols
 * - Compiler diagnostic extraction, classification, and fix suggestion
 * - Integration with DebuggerAgent for structured remediation
 */
class TestGenerator {
public:
    TestGenerator() = default;
    ~TestGenerator() = default;

    // ─── Test Generation ──────────────────────────────────────

    /**
     * Generate GoogleTest unit tests for a given list of symbols.
     * @param symbols  Parsed symbols from ASTParser
     * @param output_dir  Directory to write test file into
     * @param suite_name  GoogleTest suite name
     */
    TestGenerationResult generateTests(const std::vector<ParsedSymbol>& symbols,
                                       const std::string& output_dir,
                                       const std::string& suite_name = "AutoGenerated");

    /**
     * Generate a test scaffold for a single symbol.
     */
    GeneratedTestCase generateTestCase(const ParsedSymbol& symbol,
                                       const std::string& suite_name = "AutoGenerated") const;

    /**
     * Write generated test cases to a .cpp file.
     */
    bool writeTestFile(const TestGenerationResult& result) const;

    // ─── Diagnostic Extraction ────────────────────────────────

    /**
     * Parse raw compiler output (GCC, Clang, MSVC) into structured diagnostics.
     */
    DiagnosticsReport parseDiagnostics(const std::string& compiler_output,
                                       const std::string& compiler = "gcc") const;

    /**
     * Run the build command and capture diagnostics.
     * @param build_command  e.g. "cmake --build build --target aios_tests"
     * @param working_dir    project root directory
     */
    DiagnosticsReport buildAndCapture(const std::string& build_command,
                                      const std::string& working_dir) const;

    /**
     * Convert a diagnostics report into remediation suggestions for DebuggerAgent.
     * Returns a JSON-serializable string of structured actions.
     */
    std::string toRemediationActions(const DiagnosticsReport& report) const;

private:
    std::string generateIncludeGuard(const std::string& suite_name) const;
    std::string generateIncludes(const std::vector<GeneratedTestCase>& cases) const;
    std::string generateTestBody(const ParsedSymbol& symbol) const;
    std::string generateArgsPlaceholders(const std::vector<std::string>& param_types) const;
    std::string generateReturnAssertion(const std::string& return_type) const;

    DiagnosticsReport parseGccClangOutput(const std::string& output) const;
    DiagnosticsReport parseMsvcOutput(const std::string& output) const;
    DiagnosticSeverity parseSeverityToken(std::string_view token) const;
    std::string suggestFix(const CompilerDiagnostic& diag) const;
};

} // namespace aios
